# Generated by Django 4.1.7 on 2023-12-13 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0002_alter_note_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 10, 22, 46, 402383, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
