# Generated by Django 4.1.7 on 2023-12-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0005_alter_note_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='body',
            new_name='content',
        ),
    ]
